### ISSUE TITLE
Using Ambrose with Hive 0.14

### ISSUE THREAD

**Issue by goyalr41** [twitter/ambrose#183]
Hi,

I am trying to use Ambrose with Hive version 0.14 but I am getting `NoSuchMethodError`. I checked the code for Hive 0.13 and 0.14 and it seems like in 0.14 this method is deprecated. Ambrose is calling it at this [line](https://github.com/twitter/ambrose/blob/master/hive/src/main/java/com/twitter/ambrose/hive/AmbroseHiveFinishHook.java#L123). Also adding the complete stacktrace:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.ql.session.SessionState.getLastMapRedStatsList()Ljava/util/List;
	at com.twitter.ambrose.hive.AmbroseHiveFinishHook.displayStatistics(AmbroseHiveFinishHook.java:123)
	at com.twitter.ambrose.hive.AmbroseHiveFinishHook.postDriverRun(AmbroseHiveFinishHook.java:81)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1208)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1006)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:996)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:247)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:199)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:410)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:345)
	at org.apache.hadoop.hive.cli.CliDriver.processReader(CliDriver.java:443)
	at org.apache.hadoop.hive.cli.CliDriver.processFile(CliDriver.java:459)
	at org.apache.hadoop.hive.cli.CliDriver.processInitFiles(CliDriver.java:493)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:730)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:677)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
``` 

**Does Ambrose works only till hive 0.13 or is there any workaround for it?**

Thanks,
Raman

**Comment by billonahill** [comment]
Since Hive changed it's API the way around this would be to create a new Hive shim layer that is able to handle bother the 0.13 API and the newer API. I'm unaware of any efforts in place to do that.

**Comment by goyalr41** [comment]
Can you please explain what needs to be changed? I mean Hive deprecated this method but did they provide any other method for it or something else?

Thanks,
Raman
